# Generated by Django 2.2.7 on 2019-12-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(default='123', max_length=225)),
                ('quiz_class', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('status', models.CharField(default=1, max_length=1)),
                ('user_class', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=2)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.User')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('choos1', models.CharField(max_length=500)),
                ('choos2', models.CharField(max_length=500)),
                ('choos3', models.CharField(max_length=500)),
                ('choos4', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=500)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Quiz')),
            ],
        ),
    ]
